### ISSUE TITLE
_reactNativeReanimated.default.proc is not a function

### ISSUE THREAD

**Issue by nextriot** [terrysahaidak/react-native-retween#1]
Hi @terrysahaidak. Awesome idea! 
Any attempt to make Reanimated easier to digest – I'm all for it :)

I followed your steps using an Expo build, and received the following error: `_reactNativeReanimated.default.proc is not a function` the error is at: `runTiming.ts:13:21`

Any idea where I'm going wrong? 
Here are the relevant details from my `package.json` file and `app.json` respectively.

```
"react-native-reanimated": "~1.2.0",
"react-native-retween": "^0.2.0",
"expo": "^35.0.0",
"react": "16.8.3",
 "react-dom": "16.8.3",
"react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
```

```
"sdkVersion": "35.0.0",
```

And here's the full component code for completeness:

```
import React, { useRef, useEffect, useState } from 'react'
import { Text } from 'react-native'
import Animated from 'react-native-reanimated'
import { useTween } from 'react-native-retween'

import styled from 'styled-components/native'
import { sharedStyles } from 'theme'

type PromptType = 'success' | 'warn' | 'error'

interface Props {
  children: React.ReactNode
  isVisible: boolean
  type?: PromptType
}

const mapColor = (type: PromptType = 'success') => {
  switch (type) {
    case 'error':
      return 'red'
    case 'warn':
      return 'yellow'
    case 'success':
      return 'green'
    default:
      return 'green'
  }
}

const animConfig = {
  spring: {
    mass: 1,
  },
  from: {
    opacity: 0,
  },
  to: {
    opacity: 1,
  },
}

const FormPrompt = ({ children, isVisible }: Props) => {
  const { play, values, stop } = useTween(() => animConfig)
  useEffect(() => {
    play(isVisible)
  }, [isVisible])
  return (
    <Animated.View style={values}>
      <Wrapper>
        <Text>{children}</Text>
      </Wrapper>
    </Animated.View>
  )
}

const Wrapper = styled.View<Pick<Props, 'type'>>`
  padding: ${sharedStyles.spacing.md};
  border-radius: ${sharedStyles.bdrs.sm};
  background-color: ${props => mapColor(props.type)};
`

export default FormPrompt
```

Let me know if there's anything else I can provide.

**Comment by terrysahaidak** [comment]
Hi, thanks, but unfortunately it won't work with expo 35 (I should have been more clear in readme), since it has an old version of reanimated which has no proc.

**Comment by terrysahaidak** [comment]
The solution here is to add some kind of check for proc existing in Animated, and if it's not just don't use it, PRs are welcome :)

**Comment by nextriot** [comment]
Thanks for the quick reply! 2 questions then:

• Which version of Expo are you using to make it work? It looks like SDK 35 is the latest?
• Is there no code within this library which uses `proc`? If so, what would the calls to `proc` be replaced with?

**Comment by terrysahaidak** [comment]
I don't use expo, example is using plain RN :) I mentioned in installation steps the expo problem, but it wasn't clear, sorry.

The lib is using proc in few places, but it can be replaced with non-proc version for the version of reanimated without it. Proc provides us a better performance so it can't be just dropped in favor of expo.

**Comment by terrysahaidak** [comment]
@nextriot I've added PR with a fix, please check it out and test with the expo, let me know if it works, thanks.

**Comment by nextriot** [comment]
That's great @terrysahaidak! Thanks.
There was an error in the path referencing `maybeProc` in the `runTiming` and `runSpring` files.
I've made a PR with the fix. With that amendment everything works great on Expo :)

**Comment by terrysahaidak** [comment]
@nextriot I've just noticed it and fixed, also pushed to that branch

**Comment by nextriot** [comment]
haha you're a quicker shot than I am. Feel free to ignore mine.
If you're happy to push it to master, I'll gladly close this issue. 
Thanks a bunch @terrysahaidak

**Comment by terrysahaidak** [comment]
Sure, will deploy it as 0.3.0.

**Comment by terrysahaidak** [comment]
Should be out

**Comment by terrysahaidak** [comment]
By the way, check out the accordion example

**Comment by nextriot** [comment]
> By the way, check out the accordion example

Will do 👍
